### ISSUE TITLE
lines not formatted with python syntax highlighting

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/astronomy-python#10]
There are a few lines of code in lesson 7 where the code is showing up as `plain text` rather than with Python syntax highlighting. Two examples:

`plt.gca().tick_params(direction='in')`

`plt.style.use('fivethirtyeight')`

The second example is followed immediately by an empty code chunk.

**Comment by AllenDowney** [comment]
Those are cases where the code is part of a text cell, rather than a code cell.

In theory, I could modify the translator to catch these and translate them, but it might be better to handle them manually after we're done with the automated part of the translation.
