### ISSUE TITLE
Section on Accessibility in Visualizations Episode

### ISSUE THREAD

**Issue by catherine-martlin** [datacarpentry/astronomy-python#129]
While the summary of episode 8 mentions that one should keep accessibility in mind it doesn't go into depth on what that means specifically. It would be great to add a section about this that covers issues such as colorblindness, being thoughtful regarding image size and annotation size, considering how things will look in print vs. on various electronic devices, etc. 

Are there any resources that we can link to regarding this as well? Article or paper?

**Comment by rkotulla** [comment]
I've liked the write-up by the Cherenkov Telescope Array on avoiding color-maps for the most common red-green colorblindness: https://www.cta-observatory.org/wp-content/uploads/2020/10/CTA_ColourBlindness_BestPractices-1.pdf
Their astrodiversity project may have even more useful advice: https://www.cta-observatory.org/outreach-education/astrodiversity/

The cividis colormap they suggest is in turn based on this PLOS ONE article (https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0199239) and even has a github-repo (https://github.com/benmaier/cividis -- not sure if this is included in matplotlib natively).

Another good summary is the one by Kenneth Moreland, again on using and optimizing colormaps: https://www.kennethmoreland.com/color-advice/
