### ISSUE TITLE
Self organized workshop description

### ISSUE THREAD

**Issue by abostroem** [datacarpentry/astronomy-python#133]
Right now the curriculum stands out on the self organized workshop page as either not having a description or not being associated with DC

<img width="714" alt="Screen Shot 2022-05-31 at 10 16 36 PM" src="https://user-images.githubusercontent.com/2522639/172231503-95c40627-82a9-44b1-851a-302ae3da5804.png">

**Comment by abostroem** [comment]
thank you - I wasn't sure where to look

**Comment by ErinBecker** [comment]
@fmichonneau got the fix in already! 🎉
