### ISSUE TITLE
Update Query Result numbers in Various Exercise Solutions

### ISSUE THREAD

**Issue by catherine-martlin** [datacarpentry/astronomy-python#149]
@yotam-stsci and I noticed some of the solutions have out of date numbers for the query results - will review and report here what the updated values are and can edit to fix after our workshop is over today.

**Comment by catherine-martlin** [comment]
Example - https://datacarpentry.org/astronomy-python/06-join/index.html#exercise-15-minutes-1 - says 3725 results, but it appears to have updated to 4300. 

Will do a full run of all examples later today and submit a PR with updated numbers so participants don't get worried when a different number appears.

**Comment by catherine-martlin** [comment]
This may also be affecting the sizes of the files we list at the end of various episodes so we should double check those too.

**Comment by catherine-martlin** [comment]
Very  small fix needed in https://datacarpentry.org/astronomy-python/08-plot/index.html#exercise-20-minutes --> all other `plt.annotate` isn't in code style while the other ones are

**Comment by abostroem** [comment]
@catherine-martlin submitted a PR for everything but the last comment.
