### ISSUE TITLE
gd1koposov10 existing in SkyCoord

### ISSUE THREAD

**Issue by aferte** [datacarpentry/astronomy-python#193]
Hello, 

Regarding Episode 2 on coordinates  https://datacarpentry.org/astronomy-python/02-coords/,  specifying frame='gd1koposov10' seems to work well in SkyCoord, instead of using the gala gd1 frame.

Thank you!

**Comment by abostroem** [comment]
Do we still need it for the reflex correction or is that part of astropy? That would be my only concern.

**Comment by rkotulla** [comment]
I've looked into this reflex-correction a bit more -- it's implemented as a stand-alone function, using onlyl other astropy functions under the hood. Since that's all we would need from gala we could just include this one specific function with the rest of the lesson material and get rid of the gala dependency that way.

**Comment by abostroem** [comment]
I don't think that `GD1Koposov` is an astropy coordinate frame in the sense that we can convert to it. For instance, the following does NOT work for me 
```
from astropy.coordinates import GD1Koposov10
```
and without that, I'm not sure how do the following:
```
coord_gd1 = coord_icrs.transform_to(gd1_frame)
```

Additionally, while it is tempting to remove a dependency by copying the reflex correction to a stand alone function, I think this demonstrates a poor coding practice. If a bug is discovered in the `gala` code, we won't get the update. Unless we encounter issues with the gala installation, I vote we keep the lesson as is and close this issue

**Comment by rkotulla** [comment]
I just tested the original idea using my astropy (version 5.2.2), and the frame='gd1koposov10' option just returns an error now (ValueError: Coordinate frame name "gd1koposov10" is not a known coordinate frame (['altaz'...... ), so it seems like this feature was removed from astropy at some point (same goes for the latest astropy 6.0.0 version).  I suggest we close this issue for now -- if this ever makes it into astropy for good we can return and re-evaluate.
