### ISSUE TITLE
Should "table" be "dataframe"?

### ISSUE THREAD

**Issue by HannoSpreeuw** [datacarpentry/astronomy-python#200]
In the [Photometry episode](https://datacarpentry.org/astronomy-python/07-photo/index.html), there is a paragraph about a plotting function:
```
To do this we will change our variable name from candidate_df to the more generic table.
```
Should `table` be `dataframe`, since `dataframe` is the name of the input variable to the plotting function?

**Comment by ErinBecker** [comment]
Good catch @HannoSpreeuw!
