### ISSUE TITLE
import gala.coordinate

### ISSUE THREAD

**Issue by pbtoubol** [datacarpentry/astronomy-python#210]
### What is the problem?

I have download the package astronomy-python of https://datacarpentry.org/astronomy-python/ 
The installation is OK but when I want to check my installation, and i try :

'import gala.coordinates as gc'

 I receive this message:

ImportError: cannot import name 'update_default_config' from 'astropy.config.configuration' (/home/pierre-bernard/anaconda3/envs/AstronomicalData/lib/python3.12/site-packages/astropy/config/configuration.py)

Do you have an idea ? thanks

**Comment by abostroem** [comment]
Can you please let me know what OS you are using and the version of astropy and gala that you have installed? You can access this information by starting up a python session and typing:
```
import astropy
print(astropy.__version__)
import gala 
print(gala.__version__)
```
It is possible the gala import will produce the same error you got above, in which case don't worry about getting the version.

**Comment by pbtoubol** [comment]
I followed the advice of adrian price-whelan on Slack. I have downloaded the last version of GALA (development version) , with
`pip install git+https://github.com/adrn/gala`

...and it run perfectly ! 
My astropy.version is 6.0.0
and my new gala version is 1.7.2.dev45+g3aab5f14

Thank's . It's a very great job. I plan to use it in my Astronomical Association in France ( after translated)

**Comment by abostroem** [comment]
Thanks for sharing your solution @pbtoubol. If you teach this lesson is would be great to submit it as a self organized workshop to the Carpentries so that we can track its use.
