### ISSUE TITLE
Problem with exercise syntax

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/astronomy-python#5]
I think all of the exercises are missing the line that marks the start of the solution:

`> >  ## Solution`

Example: 
![Screen Shot 2021-01-14 at 3 42 50 PM](https://user-images.githubusercontent.com/19176319/104662255-43026d80-567f-11eb-8c38-834d1b075178.png)

> ## Exercise
> 
> One of the other tables we'll use is
> `gaiadr2.panstarrs1_original_valid`.  Use `load_table` to get the
> metadata for this table.  How many columns are there and what are
> their names?
> > 
> > ~~~
> > 
> > meta2 = Gaia.load_table('gaiadr2.panstarrs1_original_valid')
> > print(meta2)
> > 
> > for column in meta2.columns:
> >     print(column.name)
> > ~~~
> > {: .language-python}
> {: .solution}
{: .challenge}

Needs to be:

> ## Exercise
> 
> One of the other tables we'll use is
> `gaiadr2.panstarrs1_original_valid`.  Use `load_table` to get the
> metadata for this table.  How many columns are there and what are
> their names?
> >  ## Solution
>>
> > ~~~
> > 
> > meta2 = Gaia.load_table('gaiadr2.panstarrs1_original_valid')
> > print(meta2)
> > 
> > for column in meta2.columns:
> >     print(column.name)
> > ~~~
> > {: .language-python}
> {: .solution}
{: .challenge}

**Comment by AllenDowney** [comment]
This should be fixed now.  I've pushed updated lessons and spot-checked the exercises.

@ErinBecker, please take a look and let me know if you spot any remaining problems with the exercises.
