### ISSUE TITLE
Plots not rendering in lesson 3

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/astronomy-python#6]
![Screen Shot 2021-01-14 at 3 50 22 PM](https://user-images.githubusercontent.com/19176319/104662724-49ddb000-5680-11eb-821b-18caa101e3dc.png)

And others

**Comment by AllenDowney** [comment]
I have taken a step toward solving this.  The current Markdown includes code to include the figures, but it looks like it's not currently working.

@ErinBecker I could use some help debugging this.  In the formatting instructions at

https://carpentries.github.io/lesson-example/04-formatting/index.html

I don't see any guidance about how images should be included.

Some of the figures are included using HTML, and those are working.

Other figures use Markdown like this

```
![png](05-join_files/05-join_10_0.png)
```

to refer to local files.  Those don't seem to work.

**Comment by ErinBecker** [comment]
Closed with #19 and #20
