### ISSUE TITLE
Tell learners to move student_download from download to desktop or another location

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/astronomy-python#67]
In setup, learners download the file `student_download.zip`. We have them upzip the file and start working with the component files, but don't tell them to move it out of their Downloads folder. We should tell them to put it somewhere else. 🙂

**Comment by abostroem** [comment]
I'm a little concerned that not knowing people's file system will make this difficult. Is it still useful to tell them to move it to wherever they want it? Is there precedent in other lessons?

**Comment by abostroem** [comment]
In the ecology workshop have learners move to Desktop.
