### ISSUE TITLE
Move isochrone to discussion?

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/astronomy-python#69]
Right now there is an `isochrone.md` file, but it doesn't show up on the rendered website because it is lacking a page title (example below).

```
---
title: Prerequisites
---
```

Two options are:
1) Add a page title to that .md file. It will then appear as a separate page within the Extras drop-down menu.
2) Move the contents of that .md file to `discussion.md` (which is currently empty).

**Comment by abostroem** [comment]
I don't have strong feelings about this. Maybe its easiest is to add a title: Making the Isochrone

**Comment by ErinBecker** [comment]
I'm seeing the isochrone page rendering at https://datacarpentry.org/astronomy-python/calculating_MIST_isochrone/. If this looks right to you @abostroem, we can close this issue.

**Comment by ErinBecker** [comment]
Looks like it needs to point to https://datacarpentry.org/astronomy-python/calculating_MIST_isochrone/index.html instead of https://datacarpentry.org/astronomy-python/_extras/calculating_MIST_isochrone. I'll put in a fix

**Comment by abostroem** [comment]
This may also be references in the instructor notes incorrectly

**Comment by ErinBecker** [comment]
I fixed that one too :-)

Not seeing any other references to this file in the repo, so I'll go ahead and merge that PR.
