### ISSUE TITLE
Extraneous Python code block at end of lesson 3

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/astronomy-python#7]
![Screen Shot 2021-01-14 at 3 51 45 PM](https://user-images.githubusercontent.com/19176319/104662821-72fe4080-5680-11eb-8a6e-d85ca567674e.png)

**Comment by ErinBecker** [comment]
Also lesson 4 but not lesson 1 or 2

**Comment by AllenDowney** [comment]
Every time you run a notebook, it adds an empty cell at the end (if there isn't one).  Might have to remove by hand.
