### ISSUE TITLE
Episode 2: Inconsistent variable name in "Selecting a region" section

### ISSUE THREAD

**Issue by jdeplaa** [datacarpentry/astronomy-python#70]
Dear maintainers,

In [Episode 2: Selecting a region](https://github.com/datacarpentry/astronomy-python/blob/gh-pages/_episodes/02-coords.md#selecting-a-region), I found an inconsistency in the used variable name `cone_query`. The first code block defines `cone_query`:
```
cone_query = """SELECT 
TOP 10 
source_id
FROM gaiadr2.gaia_source
WHERE 1=CONTAINS(
  POINT(ra, dec),
  CIRCLE(88.8, 7.4, 0.08333333))
"""
```
but in the next code block, this variable is suddenly called `query_cone` in the `Gaia.launch_job()` call:
```
from astroquery.gaia import Gaia

cone_job = Gaia.launch_job(query_cone)
cone_job
```
Copying this code into a notebook obviously results in an error, so could you correct this by renaming one of the two to make them consistent?

Many thanks and cheers, Jelle.

**Comment by rudyphd** [comment]
Closed by [PR #72](https://github.com/datacarpentry/astronomy-python/pull/72).
