### ISSUE TITLE
Episode 4: gd1_frame definition missing in new notebook

### ISSUE THREAD

**Issue by jdeplaa** [datacarpentry/astronomy-python#71]
Dear maintainers,

At the top of [Episode 4](https://github.com/datacarpentry/astronomy-python/blob/gh-pages/_episodes/04-select.md), an instruction is given which modules and variables need to be loaded if the episode is started with a new notebook. In this instruction, the definition of the variable `gd1_frame` is missing.

Later in the episode, in the section "Assembling the query", `gd1_frame` is being used in a call to `SkyCoord()`. If `gd1_frame` is not defined, this leads to an error. 

Could you add the line `gd1_frame = GD1Koposov10()` to the instructions for new notebooks at the start of this Episode to fix the issue?

Thanks and cheers, Jelle de Plaa.

**Comment by rudyphd** [comment]
Closed by [PR #73](https://github.com/datacarpentry/astronomy-python/pull/73)
