### ISSUE TITLE
Python code chunks not showing with syntax highlighting in exercise

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/astronomy-python#8]
This is in lesson 5 (joins):

![Screen Shot 2021-01-14 at 3 54 52 PM](https://user-images.githubusercontent.com/19176319/104663006-e3a55d00-5680-11eb-8334-309b5e271687.png)

**Comment by AllenDowney** [comment]
Same as #10 and #9; might be best to fix manually.
