### ISSUE TITLE
We can put info about invert_yaxis in callout

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/astronomy-python#9]
Lesson 6 has "gotcha" about invert_yaxis that can go into a callout. Can also format the code chunks with python syntax highlighting within callout.

**Comment by AllenDowney** [comment]
Related to #10 , formatting code that's embedded in a text block is hard to automate; might have to do by hand.

**Comment by ErinBecker** [comment]
I tried to put this into an "Error" chunk using `{: .error}` as documented [in the lesson-example](https://carpentries.github.io/lesson-example/04-formatting/index.html) but it's not rendering as a callout: 

![Screen Shot 2021-04-21 at 11 22 31 AM](https://user-images.githubusercontent.com/19176319/115602898-5895bd80-a294-11eb-9e1d-2f094ec0a2f8.png)

@zkamvar - any advice? :-)

**Comment by zkamvar** [comment]
The `.error` attribute is only for code. It does not get applied to blocks. A better solution may be to make this a callout block and add in the error as a code block under the python block.

**Comment by zkamvar** [comment]
For reference, you are referring to this bit of the text?

https://github.com/datacarpentry/astronomy-python/blame/2a508e73899fa480d3b3d24a8ec51d64d5724be4/_episodes/06-photo.md#L155-L168

**Comment by ErinBecker** [comment]
Thank you @zkamvar. That is EXACTLY what I needed to know!! 😄  I'll get that fixed up.

**Comment by abostroem** [comment]
We no longer use invert_yaxis and now use ylim
