### ISSUE TITLE
Add kernel installation instructions to setup? 

### ISSUE THREAD

**Issue by bmg-pcl** [datacarpentry/astronomy-python#95]
In the setup instructions, learners are guided through a fresh install of anaconda. 

https://datacarpentry.org/astronomy-python/setup.html

I came at it slightly differently since I have anaconda and other conda venvs present. Creating the new env with
**conda env create -f environment.yml**
left me unable to 

Should we include the instructions to make a new kernel to jupyter, ie. 

$ python -m ipykernel install --user --name=AstronomicalData

**Comment by abostroem** [comment]
Hi @bmg-pcl , I'm not sure I understand exactly what failed. The set up directions start with the `conda env create -f environment.yml` command that you mention. Did that not work for you? Could you provide a few more details on the failure?

Thanks!

**Comment by bmg-pcl** [comment]
Sorry, that was a little unclear!

On my setup:

1. Setup was successful at creating the AstronomicalData conda env
2. Jupyter did *not* have a kernel available for this env, so packages weren't available from jupyter.  
3. I manually created the kernel 'astro' to remediate. 

Screenshot below for result of #3. I don't know if this was a one-off - now that it's set up I can't reproduce here - but we don't mention kernels anywhere else so it could be a point of confusion. 

![image](https://user-images.githubusercontent.com/57019178/142240448-676fd89d-0c46-4aba-be22-3c8cd9dbc840.png)

**Comment by abostroem** [comment]
This is an issue I see too but that not many people have encountered. I think we were trying to get around it by starting the notebook from the AstronomicalData environment (maybe we should also rename this). Was this the workflow that you followed?

**Comment by bmg-pcl** [comment]
Doesn't seem like it's affecting any current workshop participants but I'm glad it's not just me! 

I did indeed start from within the AstronomicalData env. 

After current workshop is complete I can try to recreate. I think my full repro steps would be? 

1. Environment: x64 Windows 10 Build 19043, pre-existingAnaconda 5.x installation; Mozilla Firefox 94.0.1 browser
2. Downloaded learners' student_download.zip from https://zenodo.org/record/5637441/files/student_download.zip?download=1 and unzipped. 
3. In Terminal with base anaconda env, created AstronomicalData env via conda env create -f environment.yml per setup instructions at https://datacarpentry.org/astronomy-python/setup.html
4. Activated new env via `conda activate AstronomicalData`
5. Invoked notebook via `jupyter notebook` command.
6. Opened `test_setup.ipynb` notebook from within jupyter. 
7. Notebook failed to run on `from wget import download` ; none of the packages that weren't part of my base conda env were present.

**Comment by bmg-pcl** [comment]
A call-out or a setup FAQ would work, but I'm wondering - do you think it's better to declare an astro kernel specifically and get learners to select it when they open jupyter? 

It's kind of a subtle part of the notebook concept and explicit might be better than implicit in this case.

**Comment by abostroem** [comment]
Would you propose writing something up in the set up instructions? I'd be happy to take a look at it.

However, my concern is that we are using Jupyter as a tool - not the main lesson - so I want to make sure that we don't get too side tracked and that we don't create more installation issues (for instance would they need to install ipykernel?). If this issue occurred more frequently in the lesson delivery - then I would say we should teach it - but for now I am fine using the workflow of switching environments and then opening a notebook (as long as that continues to work for most learners)

**Comment by abostroem** [comment]
Create a call out in the set up instructions
