### ISSUE TITLE
Update teaching time for episode 8: Visualization

### ISSUE THREAD

**Issue by annajiat** [datacarpentry/astronomy-python#98]
In the episode 8: Visualization
https://datacarpentry.org/astronomy-python/08-plot/index.html
Both teaching time and exercises are listed as 65 minutes each. However, the episode is mostly exercises. Combinedly, it is might take less than 75 minutes. Should we update teaching time to may be something like 10 minutes?

**Comment by abostroem** [comment]
We are taking careful notes on timing during the beta - we will use that to update the timing

**Comment by abostroem** [comment]
We ran out of time in the workshop so I'm going to close this issue. We can reopen if timing is a reoccurring issue
